const faqs = [
  {
    q: 'Is ResumeAI truly ATS-compatible?',
    a: 'Yes. Every resume generated by ResumeAI is optimized for Applicant Tracking Systems. Our AI understands the parsing rules used by major ATS platforms and structures your resume accordingly, including proper heading formats, keyword density, and clean formatting.',
  },
  {
    q: 'Does it work for every role?',
    a: 'Absolutely. ResumeAI works for any industry or job level — from entry-level positions to C-suite executives. Simply paste the job description and let the AI tailor your resume to match.',
  },
  {
    q: 'Can I use my existing resume?',
    a: 'Yes. Upload your existing resume in PDF, DOCX, or TXT format and ResumeAI will analyze it, extract your experience, and use it as the basis for tailoring.',
  },
];


export function FaqSection() {
  return (
    <section
      className="py-24"
      aria-labelledby="faq-heading"
      style={{ background: 'var(--color-surface-container-low)' }}
    >
      <div className="container-app">
        <div className="text-center mb-12 flex flex-col items-center gap-3">
          <span className="badge badge-muted">FAQ</span>
          <h2
            id="faq-heading"
            className="text-headline-md"
            style={{ color: 'var(--color-on-surface)' }}
          >
            Frequently Asked Questions
          </h2>
        </div>

        <div
          className="flex flex-col gap-3"
          style={{ maxWidth: '720px', margin: '0 auto' }}
        >
          {faqs.map((faq, i) => (
            <details
              key={i}
              className="card-surface group"
              style={{ padding: '0' }}
            >
              <summary
                className="flex items-center justify-between cursor-pointer list-none p-5 font-medium"
                style={{
                  fontFamily: 'var(--font-display)',
                  fontSize: '15px',
                  color: 'var(--color-on-surface)',
                }}
              >
                {faq.q}
                <span
                  className="ml-4 shrink-0 text-lg transition-transform group-open:rotate-45"
                  style={{ color: 'var(--color-primary)' }}
                >
                  +
                </span>
              </summary>
              <div
                className="px-5 pb-5 text-body-md"
                style={{ color: 'var(--color-text-muted)' }}
              >
                {faq.a}
              </div>
            </details>
          ))}
        </div>
      </div>
    </section>
  );
}
